### ISSUE TITLE
Bugs when building the latest version

### ISSUE THREAD

**Issue by UUSR** [Avazart/LibraryCollector#2]
[https://github.com/Avazart/LibraryCollector/tree/lc_js](https://github.com/Avazart/LibraryCollector/tree/lc_js)
When building I get errors:

> C:\SRC\LibraryCollector-lc_js\LibraryCollector-lc_js\wrappers\dir.cpp:149: ошибка: invalid conversion from 'QFlags<QDir::Filter>::Int {aka int}' to 'Dir::Filter' [-fpermissive]
   Dir::Filters filters_=  (int)dir_.filter();

> C:\SRC\LibraryCollector-lc_js\LibraryCollector-lc_js\wrappers\dir.cpp:155: ошибка: invalid conversion from 'QFlags<Dir::Filter>::Int {aka int}' to 'QDir::Filter' [-fpermissive]
   QDir::Filters filter_=  (int)filter;

> C:\SRC\LibraryCollector-lc_js\LibraryCollector-lc_js\wrappers\dir.cpp:161: ошибка: invalid conversion from 'QFlags<QDir::SortFlag>::Int {aka int}' to 'Dir::SortFlag' [-fpermissive]
   Dir::SortFlags sorting_=  (int)dir_.sorting();

and so on...

**Comment by Avazart** [comment]
fixed
