### ISSUE TITLE
Ошибка в скриптах

### ISSUE THREAD

**Issue by set01q** [Avazart/LibraryCollector#4]
В скрипте Qt5.14.2_win_msvc2017_mingw73_32.js (возможно и в других) возникает ошибка: [js] Error at line #68 : ReferenceError: lib is not defined
Может там должно быть absolutePath(libs[i]) вместе absolutePath(lib)

Может ещё в isSSL добавить libcrypto для поддержки x64:
return baseName(libName).match(/libeay|libssl|libcrypto|ssleay\d*/i)

**Comment by set01q** [comment]
В https://github.com/Avazart/LibraryCollector/blob/master/utils/file_functions.cpp в строке 22 неправильно передаются аргументы и получается эта проверка чувствительна к регистру. Надо так:
return !nativePath.indexOf( nativeDir, 0, Qt::CaseInsensitive );

**Comment by set01q** [comment]
https://github.com/Avazart/LibraryCollector/pull/5

**Comment by Avazart** [comment]
Спасибо!
